### ISSUE TITLE
Compatibility issues with ZF3

### ISSUE THREAD

**Issue by drgomesp** [zendframework/zend-cache#117] opened 2016-10-25 12:29 UTC
Hello everyone.

I'm currently running through the process of migrating my ZF2 application to ZF3. I got stuck in a nasty issue which I cannot get around. 

Essentially, when Memcached is called for the first time during the application bootstrap phase, the extension throws a response error code (@see http://php.net/manual/en/memcached.getresultcode.php) `RES_HOST_LOOKUP_FAILURE`.

However, if I simply try to create a server and connect, set and get a key via `php -a`, I'm able to do it. Do we have support for ZF3 here? Or for Memcached?

**Comment by marc-mabe** [comment] 2016-10-26 19:29
@drgomesp zend-cache should be fully compatible with zend-eventmanager, zend-servicemanager and zend-stdlib since version 2.6.1.

`RES_HOST_LOOKUP_FAILURE` means that the DNS lookup failed. Please recheck your host setup and debug what values gets used here: https://github.com/zendframework/zend-cache/blob/master/src/Storage/Adapter/MemcachedResourceManager.php#L163 and report back if you thing zend-cache does something wrong incl. your configuration and findings.

Thanks

**Comment by Ocramius** [comment] 2016-10-26 23:25
Duplicate of zendframework/zendframework#7742

Issue spawns from doctrine caching, apparently.

Closing here, as it's cross-posted.

**Closed by Ocramius** 2016-10-26 23:25 UTC
Labels: duplicate
