### ISSUE TITLE
array_key_exists() error when updating from 2.5.3 to 2.6

### ISSUE THREAD

**Issue by avasa** [zendframework/zend-cache#72] opened 2016-02-12 12:33 UTC
Error: 

array_key_exists(): The first argument should be either a string or an integer

Calling:

```php
$config['cache'] = 'adapter' => [
    'name' => 'memcached',
            'options' => [
                'servers' => [
                    [
                        'host' => 'localhost',
                        'port' => '11211',
                    ],
                ],
            ],
        ];

$cache = StorageFactory::factory($config['cache']);
```

Stack:

```
Whoops\Exception\ErrorException: array_key_exists(): The first argument should be either a string or an integer
  File "/Users/user/dev/myapp/public/index.php", line 10, in null
    $app->run();
  File "/Users/user/dev/myapp/vendor/zendframework/zend-mvc/src/Application.php", line 314, in run
    $result = $events->trigger(MvcEvent::EVENT_DISPATCH, $event, $shortCircuit);
  File "/Users/user/dev/myapp/vendor/zendframework/zend-eventmanager/src/EventManager.php", line 214, in trigger
    return $this->triggerListeners($event, $e, $callback);
  File "/Users/user/dev/myapp/vendor/zendframework/zend-eventmanager/src/EventManager.php", line 490, in triggerListeners
    $responses->push(call_user_func($listenerCallback, $e));
  File "/Users/user/dev/myapp/vendor/zendframework/zend-mvc/src/DispatchListener.php", line 93, in onDispatch
    $return = $controller->dispatch($request, $response);
  File "/Users/user/dev/myapp/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php", line 118, in dispatch
    });
  File "/Users/user/dev/myapp/vendor/zendframework/zend-eventmanager/src/EventManager.php", line 214, in trigger
    return $this->triggerListeners($event, $e, $callback);
  File "/Users/user/dev/myapp/vendor/zendframework/zend-eventmanager/src/EventManager.php", line 490, in triggerListeners
    $responses->push(call_user_func($listenerCallback, $e));
  File "/Users/user/dev/myapp/module/myapp/src/Controller/CliController.php", line 44, in onDispatch
    $viewModel = parent::onDispatch($e);
  File "/Users/user/dev/myapp/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php", line 82, in onDispatch
    $actionResponse = $this->$method();
  File "/Users/user/dev/myapp/module/MyModule/src/Controller/Cli/MyModuleController.php", line 29, in importAction
    $cache = $this->getCache();
  File "/Users/user/dev/myapp/module/MyModule/src/Controller/Cli/MyModuleTrait.php", line 24, in getCache
    return StorageFactory::factory($config['cache']);
  File "/Users/user/dev/myapp/vendor/zendframework/zend-cache/src/StorageFactory.php", line 72, in factory
    $adapter = static::adapterFactory((string) $adapterName, $adapterOptions);
  File "/Users/user/dev/myapp/vendor/zendframework/zend-cache/src/StorageFactory.php", line 149, in adapterFactory
    $adapter->setOptions($options);
  File "/Users/user/dev/myapp/vendor/zendframework/zend-cache/src/Storage/Adapter/Memcached.php", line 131, in setOptions
    return parent::setOptions($options);
  File "/Users/user/dev/myapp/vendor/zendframework/zend-cache/src/Storage/Adapter/AbstractAdapter.php", line 130, in setOptions
    $this->getEventManager()->triggerEvent($event);
  File "/Users/user/dev/myapp/vendor/zendframework/zend-eventmanager/src/EventManager.php", line 251, in triggerEvent
    return $this->triggerListeners($event->getName(), $event);
  File "/Users/user/dev/myapp/vendor/zendframework/zend-eventmanager/src/EventManager.php", line 469, in triggerListeners
    $sharedListeners         = $this->getSharedListeners($event);
  File "/Users/user/dev/myapp/vendor/zendframework/zend-eventmanager/src/EventManager.php", line 530, in getSharedListeners
    if (!$listeners = $sharedManager->getListeners($id, $event)) {
  File "/Users/user/dev/myapp/vendor/zendframework/zend-eventmanager/src/SharedEventManager.php", line 153, in getListeners
    if (!array_key_exists($id, $this->identifiers)) {
  File "/Users/user/dev/myapp/vendor/zendframework/zend-eventmanager/src/SharedEventManager.php", line 153, in handleError
    if (!array_key_exists($id, $this->identifiers)) {
```

**Comment by macbobby** [comment] 2016-02-12 12:48
Same here. Please fix it!!!

**Comment by akumaD** [comment] 2016-02-12 12:50
Same Here

**Comment by coehmig** [comment] 2016-02-12 12:52
Same here

**Comment by weierophinney** [comment] 2016-02-12 14:20
Confirmed that this is a duplicate of #71, which identifies the root cause (improper lazy-loading of the EventManager instance). I'll have a patch shortly.

**Closed by weierophinney** 2016-02-12 14:20 UTC
Labels: bug, duplicate

**Comment by weierophinney** [comment] 2016-02-12 14:56
Those affected by this issue: can you please test the patch from #73? Tests pass against both event manager versions, and I added tests explicitly for the lazy-loading aspect, which should resolve the issue. However, I'd like verification from somebody affected.
